name: build

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pip dependencies
        run: |
          pip install build twine
          # avoid "Invalid Distribution Metadata"
          # https://github.com/pypa/twine/issues/1216#issuecomment-2606531615
          pip install --upgrade packaging
      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist
          twine check dist/*
      # Release if there is a new tag.
      - name: Publish to pypi
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
