name: build

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pip dependencies
        run: pip install build twine
      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist
          twine check dist/*
      # Release if there is a new tag.
      - name: Publish to pypi
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
